In [3]:
import tensorflow as tf
print(('Tensorflow version: {0}').format(tf.__version__))

Tensorflow version: 2.8.0


In [6]:
# create a constant tensor A
A = tf.constant([[4,3],
                 [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [8]:
# create a variable tensor V
V = tf.Variable([[3,1],
                 [5,2]])

# create a constant tensor B
B = tf.constant([[7,8],
                 [4,5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]])>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]])>

In [10]:
# concatenate columns shape ~ (row, col, other)
AB = tf.concat(values = [A, B], axis =1)
AB

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]])>

In [11]:
# concatenate rows
AB = tf.concat(values = [A, B], axis =0)
AB

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]])>